// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebShop.Data;

namespace WebShop.Migrations
{
    [DbContext(typeof(WebShopContext))]
    [Migration("20210827095416_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebShop.Models.Costumer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Costumers");
                });

            modelBuilder.Entity("WebShop.Models.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("WebShop.Models.ShoppingBag", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CostumerID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("SBCostumerID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CostumerID");

                    b.ToTable("ShoppingBags");
                });

            modelBuilder.Entity("WebShop.Models.ShoppingItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("SBagID")
                        .HasColumnType("int");

                    b.Property<int>("SIProductID")
                        .HasColumnType("int");

                    b.Property<int?>("ShoppingBagID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ShoppingBagID");

                    b.ToTable("ShoppingItems");
                });

            modelBuilder.Entity("WebShop.Models.ShoppingBag", b =>
                {
                    b.HasOne("WebShop.Models.Costumer", null)
                        .WithMany("CostumerShoppingBags")
                        .HasForeignKey("CostumerID");
                });

            modelBuilder.Entity("WebShop.Models.ShoppingItem", b =>
                {
                    b.HasOne("WebShop.Models.ShoppingBag", null)
                        .WithMany("SBShoppingItems")
                        .HasForeignKey("ShoppingBagID");
                });

            modelBuilder.Entity("WebShop.Models.Costumer", b =>
                {
                    b.Navigation("CostumerShoppingBags");
                });

            modelBuilder.Entity("WebShop.Models.ShoppingBag", b =>
                {
                    b.Navigation("SBShoppingItems");
                });
#pragma warning restore 612, 618
        }
    }
}
